name: ITP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  REPORT_FORMATTER: mocha-reporter-gha
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Ensure run.js is executable
        run: chmod +x ./bin/run.js

      - name: Run docs-generator
        run: ./bin/run.js docs-generator

      - name: Check for documentation changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "The following files have been modified:"
            git status --porcelain
            echo "Please run ./bin/run.js docs-generator command to update the documentation."
            exit 1
          fi

      - name: Audit
        run: npm audit

      - name: Lint
        run: npm run lint

      - name: Test (standalone)
        env:
          ITP_API_URL: ${{ vars.ITP_API_URL }}
          ITP_ISSUER_URL: ${{ vars.ITP_ISSUER_URL }}
          ITP_SERVICE_CLIENT_ID: ${{ vars.ITP_SERVICE_CLIENT_ID }}
          ITP_SERVICE_CLIENT_SECRET: ${{ secrets.ITP_SERVICE_CLIENT_SECRET }}
          ITP_MAILINATOR_API_KEY: ${{ secrets.ITP_MAILINATOR_API_KEY }}
        run: npm run test