name: Trigger Azure Pipeline on Release

on:
  release:
    types: [published]

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Azure DevOps Pipeline
      uses: Azure/pipelines@v1.2
      with:
        azure-devops-project-url: 'https://dev.azure.com/bentleycs/beconnect'
        azure-pipeline-name: 'iTwin.itwin-cli'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}